import { Mod, Category, Platform } from './types';

// Mock Data representing the requested "10 AAA Titles" database subset
export const MOCK_MODS: Mod[] = [
  {
    id: '1',
    title: 'Neon City Lighting Overhaul',
    gameTitle: 'Cyberpunk 2077',
    author: 'TechRunner',
    version: 'v2.1.0',
    supportedGameVersion: '2.1',
    imageUrl: 'https://picsum.photos/id/122/800/600',
    category: Category.GRAPHICS,
    platforms: [Platform.PC, Platform.XBOX, Platform.PLAYSTATION],
    downloads: 1250000,
    endorsementRate: 4.8,
    verified: true,
    description: 'Completely rewritten lighting engine for Night City. Adds ray-traced reflections to wet surfaces and improves global illumination.',
    size: '1.2 GB',
    uploadDate: '2023-11-15',
    hash: 'a1b2c3d4e5f67890abcdef1234567890',
    dependencies: [{ name: 'CyberEngineTweaks', version: '>=1.0', mandatory: true }]
  },
  {
    id: '2',
    title: 'SkyUI Revised',
    gameTitle: 'Skyrim: SE',
    author: 'NordicCode',
    version: 'v5.2.SE',
    supportedGameVersion: '1.6.640',
    imageUrl: 'https://picsum.photos/id/29/800/600',
    category: Category.UI,
    platforms: [Platform.PC, Platform.XBOX],
    downloads: 8500000,
    endorsementRate: 4.9,
    verified: true,
    description: 'The definitive interface overhaul. Optimizes the inventory system for mouse and keyboard while keeping controller support intact.',
    size: '25 MB',
    uploadDate: '2016-10-28',
    hash: 'f6e5d4c3b2a10987654321fedcba0987',
    dependencies: [{ name: 'SKSE64', version: '2.2.3', mandatory: true }]
  },
  {
    id: '3',
    title: 'Optifine Ultra',
    gameTitle: 'Minecraft',
    author: 'BlockMaster',
    version: 'HD U H9',
    supportedGameVersion: '1.20.1',
    imageUrl: 'https://picsum.photos/id/34/800/600',
    category: Category.PERFORMANCE,
    platforms: [Platform.PC],
    downloads: 15000000,
    endorsementRate: 4.7,
    verified: true,
    description: 'Boosts FPS and allows for HD textures and shaders. Essential for any modded setup.',
    size: '5 MB',
    uploadDate: '2023-08-01',
    hash: '1234567890abcdef1234567890abcdef',
    dependencies: []
  },
  {
    id: '4',
    title: 'Natural Vision Evolved',
    gameTitle: 'GTA V',
    author: 'Razed',
    version: 'Platinum',
    supportedGameVersion: '1.0.2802',
    imageUrl: 'https://picsum.photos/id/56/800/600',
    category: Category.GRAPHICS,
    platforms: [Platform.PC, Platform.PLAYSTATION, Platform.XBOX],
    downloads: 340000,
    endorsementRate: 4.9,
    verified: true,
    description: 'A work-in-progress visual overhaul mod. Numerous changes were made to the environmental weather, lighting, ambient colors, and tone mapping.',
    size: '6.4 GB',
    uploadDate: '2023-05-20',
    hash: 'abcdef1234567890abcdef1234567890',
    dependencies: [{ name: 'ScriptHookV', version: 'latest', mandatory: true }]
  },
  {
    id: '5',
    title: 'Seamless Co-op',
    gameTitle: 'Elden Ring',
    author: 'TarnishedDev',
    version: 'v1.5.1',
    supportedGameVersion: '1.10',
    imageUrl: 'https://picsum.photos/id/88/800/600',
    category: Category.QOL,
    platforms: [Platform.PC],
    downloads: 2100000,
    endorsementRate: 4.8,
    verified: true,
    description: 'Remove all boundaries of multiplayer. Play the entire game from tutorial to final boss with friends without disconnections.',
    size: '12 MB',
    uploadDate: '2023-02-14',
    hash: '0987654321fedcba0987654321fedcba',
    dependencies: []
  },
  {
    id: '6',
    title: 'HD Reworked Project',
    gameTitle: 'The Witcher 3',
    author: 'HalkHogan',
    version: 'v12.0',
    supportedGameVersion: '4.04',
    imageUrl: 'https://picsum.photos/id/96/800/600',
    category: Category.GRAPHICS,
    platforms: [Platform.PC, Platform.XBOX, Platform.PLAYSTATION],
    downloads: 5000000,
    endorsementRate: 4.9,
    verified: true,
    description: 'Improves graphics by reworking models and textures to better quality without dropping performance.',
    size: '9.3 GB',
    uploadDate: '2022-12-14',
    hash: '11223344556677889900aabbccddeeff',
    dependencies: []
  },
  {
    id: '7',
    title: 'Stardew Valley Expanded',
    gameTitle: 'Stardew Valley',
    author: 'FlashShifter',
    version: 'v1.14.24',
    supportedGameVersion: '1.5.6',
    imageUrl: 'https://picsum.photos/id/110/800/600',
    category: Category.CONTENT,
    platforms: [Platform.PC, Platform.NINTENDO],
    downloads: 1800000,
    endorsementRate: 4.9,
    verified: true,
    description: 'A fan-made expansion. Adds 27 new NPCs, 50 locations, 260 character events, and reimagined vanilla areas.',
    size: '500 MB',
    uploadDate: '2023-09-10',
    hash: 'aaabbbcccddd11122233344455566677',
    dependencies: [{ name: 'SMAPI', version: '3.18', mandatory: true }]
  },
  {
    id: '8',
    title: 'Sim Settlements 2',
    gameTitle: 'Fallout 4',
    author: 'Kinggath',
    version: 'v3.0.0',
    supportedGameVersion: '1.10.163',
    imageUrl: 'https://picsum.photos/id/133/800/600',
    category: Category.CONTENT,
    platforms: [Platform.PC, Platform.XBOX],
    downloads: 980000,
    endorsementRate: 4.6,
    verified: true,
    description: 'Sim Settlements 2 brings a new fully voiced story, new settlement building mechanics, and a host of other improvements.',
    size: '1.5 GB',
    uploadDate: '2023-01-20',
    hash: 'ffeeddccbbaa00998877665544332211',
    dependencies: [{ name: 'Workshop Framework', version: '2.3.5', mandatory: true }]
  },
  {
    id: '9',
    title: 'WASD Movement',
    gameTitle: 'Baldur\'s Gate 3',
    author: 'Ch4nKyy',
    version: 'v1.4',
    supportedGameVersion: '4.1.1',
    imageUrl: 'https://picsum.photos/id/145/800/600',
    category: Category.QOL,
    platforms: [Platform.PC],
    downloads: 450000,
    endorsementRate: 4.5,
    verified: false,
    description: 'Adds direct character movement with WASD keys and camera controls, making the game play more like a third-person RPG.',
    size: '2 MB',
    uploadDate: '2023-08-15',
    hash: '12312312312312312312312312312312',
    dependencies: [{ name: 'Native Mod Loader', version: 'any', mandatory: true }]
  },
  {
    id: '10',
    title: 'Rampage Trainer',
    gameTitle: 'Red Dead Redemption 2',
    author: 'RampageDev',
    version: 'v1.7.2',
    supportedGameVersion: '1.0.1491',
    imageUrl: 'https://picsum.photos/id/160/800/600',
    category: Category.QOL,
    platforms: [Platform.PC],
    downloads: 1100000,
    endorsementRate: 4.8,
    verified: true,
    description: 'A Single Player Trainer for Red Dead Redemption 2 with many useful features.',
    size: '8 MB',
    uploadDate: '2023-06-05',
    hash: '78978978978978978978978978978978',
    dependencies: [{ name: 'ScriptHookRDR2', version: 'latest', mandatory: true }]
  }
];